name: 'Linting and Testing'

on:
  pull_request

permissions:
  id-token: write
  contents: read

jobs:     
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:17.4.0

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: eslint
      run: |
        npm install eslint
        ./node_modules/.bin/eslint 

  testing:
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: node:17.4.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: testing
        env:
          HUSKY: 0
        run: |
          npm install
          npm test
      